Queue=[]
print("Queue after ENQUEUE Operation")
Queue.append("P")
Queue.append("r")
Queue.append("a")
Queue.append("n")
Queue.append("i")
Queue.append("t")
Queue.append("h")
Queue.append("a")
print(Queue)
print("Queue after DEQUEUE Operation of two elements")
Queue.pop(0)
Queue.pop(0)
print(Queue)
